In [78]:
# Basic libraries
import sys
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Advanced libraries for ML and Deep learning
import tensorflow as tf

# 1. Working with TensorFlow 
Interacting with TensorFlow at it would be the main framework (in conjuction with the high-level API of Keras) for modelling ANN and other machine learning algorithms. 

## **Creation of constants and variables**

In [ ]:
# Creating and displaying several constants tensors
array_a = np.array([[[1, 2],
                     [3, 4]],

                    [[5, 6],
                     [7, 8]]]) # Modifiable tensor as it is on numpy

print("Basic characterization of the tensors:",
      array_a.shape,
      array_a.dtype,
      sep="\n",
      end="\n\n"
)

# Demonstrating the basic creation of tensors
print("Basic creation of tensors",
    tf.constant([1, 2, 3, 4], dtype=tf.int8, shape=(2, 2)).numpy(),
    tf.ones((2, 2, 2)).numpy(),
    tf.ones_like(array_a).numpy(),
    tf.zeros((2, 2, 2)).numpy(),
    tf.zeros_like(array_a).numpy(),
    tf.fill([2, 2], value=7).numpy(),
sep="\n\n")

# Creating and displaying Varaible tensors
print(tf.Variable([1, 2, 3]))

Basic characterization of the tensors:
(2, 2, 2)
int64

Basic creation of tensors

[[1 2]
 [3 4]]

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]

[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]

[[[0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]]]

[[[0 0]
  [0 0]]

 [[0 0]
  [0 0]]]

[[7 7]
 [7 7]]
<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([1, 2, 3], dtype=int32)>


In [127]:
# Demonstrating the unmodifiable property of constant tensors from TensorFlow.
tensor_a = tf.constant(np.random.RandomState(13).binomial(10, 0.5, size=(2, 3, 3)), dtype=tf.int8)

try:
    tensor_a[0, 0, 0].assign(1)
except Exception as e:
    print('Warning: Constant tensors are not modifiable objects {}'.format(e))
    print(tensor_a.numpy())

# Demonstrating that Variable tensors could be modified
tensor_b = tf.Variable(tensor_a)
tensor_b[0, 0, 0].assign(1).numpy()

[[[6 4 6]
  [8 8 5]
  [5 6 6]]

 [[6 2 4]
  [3 7 4]
  [6 4 4]]]


array([[[1, 4, 6],
        [8, 8, 5],
        [5, 6, 6]],

       [[6, 2, 4],
        [3, 7, 4],
        [6, 4, 4]]], dtype=int8)

## **Performing basic matricial operations**

In [ ]:
# Evidencing basic operations
tensor_a = tf.constant([1, 2, 3, 4], dtype=tf.float16, shape=[2, 2])
tensor_b = tf.constant(np.identity(2), dtype=tf.float16)

print(
    f"Initial tensors: \n{tensor_a} \n{tensor_b}\n",
    "Operations:",
    tensor_b * 5, #Multiplication by a scalar,
    tf.transpose(tensor_a), #Transposing tensors
    tf.concat([tensor_a, tensor_a], axis=0),  #Concatenating (stacking) tensors
    tf.add(tensor_a, tensor_b).numpy(), #Elementwise addition
    tf.subtract(tensor_a, tensor_b).numpy(), #Elementwise subtraction
    tf.multiply(tensor_a, tensor_b).numpy(), #Elementwise multiplication
    tf.matmul(tensor_a, tensor_b), #Dot product
    sep="\n\n"
)

Initial tensors: 
[[1. 2.]
 [3. 4.]] 
[[1. 0.]
 [0. 1.]]


Operations:

tf.Tensor(
[[5. 0.]
 [0. 5.]], shape=(2, 2), dtype=float16)

tf.Tensor(
[[1. 3.]
 [2. 4.]], shape=(2, 2), dtype=float16)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [1. 2.]
 [3. 4.]], shape=(4, 2), dtype=float16)

[[2. 2.]
 [3. 5.]]

[[0. 2.]
 [3. 3.]]

[[1. 0.]
 [0. 4.]]

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float16)


In [106]:
# Evidencing dimmensional aggregation
ones_tensor = tf.ones([2, 3, 4]) #Tensor of two matrices, each with three rows and four columns

print(
    tf.reduce_sum(ones_tensor, axis= 0).numpy(), # Aggregation at the 3d level (first matrix plus the elements of the second matrix) 3x4 as result
    tf.reduce_sum(ones_tensor, axis= 1).numpy(), # Aggregation of the rows of each matrix and compilation in a single object 2x4 as result
    tf.reduce_sum(ones_tensor, axis= 2).numpy(), # Aggregation of the columns of each matrix and compilation in a single object 2x3 as result
    sep="\n"
)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
[[3. 3. 3. 3.]
 [3. 3. 3. 3.]]
[[4. 4. 4.]
 [4. 4. 4.]]


## **Demonstration of slicing**

**Slicing in up-to 2D**

In [ ]:
# Base tensor for performing slicing on
tensor_a = tf.Variable(np.arange(25))
tensor_a = tf.reshape(tensor_a, shape=[5, 5]) # Reshaping via tf to demonstrate such functionality
tensor_a

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])>

In [176]:
# Performing slicing on a matricial level
print(f"Getting the a particulat element {tensor_a[0, 0].numpy()}",
      f"Getting the elements from the first row {tensor_a[0].numpy()}",
      f"Getting elements from the first row that are spaced by two items {tensor_a[0][::3].numpy()}",
      f"Getting continous rows from the initial matrix \n{tensor_a[:2].numpy()}",
      f"Getting non-continous rows from the initial matrix \n{tensor_a[:3:2, :].numpy()}",
      f"Slicing based on two dimmentions \n{tensor_a[2:4, 1:3].numpy()}",
      sep="\n"
)

Getting the a particulat element 0
Getting the elements from the first row [0 1 2 3 4]
Getting elements from the first row that are spaced by two items [0 3]
Getting continous rows from the initial matrix 
[[0 1 2 3 4]
 [5 6 7 8 9]]
Getting non-continous rows from the initial matrix 
[[ 0  1  2  3  4]
 [10 11 12 13 14]]
Slicing based on two dimmentions 
[[11 12]
 [16 17]]


**Slicing tensors**

In [190]:
tensor_b = tf.constant(np.arange(18).reshape(-1, 3, 3))
print(tensor_b.numpy(),
      tensor_b.ndim,
      tensor_b.shape,
      sep="\n\n")

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]

3

(2, 3, 3)


In [ ]:
print(f"Getting a particular element form the 3D tensor: {tensor_b[0, 1, 1].numpy()}",
      f"Extracting a 1D row: {tensor_b[0, 1].numpy()}",
      f"Extracting a 2D row: {tensor_b[:, 1].numpy()}",
      f"Extracting several elements: {tensor_b[:, ::2, :2].numpy()}",
      sep="\n"
)

Getting a particular element form the 3D tensor: 4
Extracting a 1D row: [3 4 5]
Extracting a 2D row: [[ 3  4  5]
 [12 13 14]]
Extracting several elements: [[[ 0  1]
  [ 6  7]]

 [[ 9 10]
  [15 16]]]


# 2. Training base ML models with keras